openapi: "3.1.0"
info: 
  title: "Home at Home API"
  version: "1.0.0"
servers:
  - url: "/"
paths: {}
components:
  schemas:
    Location:
      required: ["name"]
      type: "object"
      properties:
        _id:
          type: "string"
          description: "The location's unique identifier"
        shortId:
          type: "string"
          description: "A shorter, human-readable identifier"
        name:
          type: "string"
          description: "The name of the location"
        descripion:
          type: "string"
          description: "A description of the location"
        address:
          type: "string"
          description: "The physical address of the location"
    Space:
      required: ["name", "location"]
      type: "object"
      properties:
        _id:
          type: "string"
          description: "The space'S long UUID"
        shortId:
          type: "string"
          description: "A shorter, human-readable identifier"
        name:
          type: "string"
          description: "The name of the space"
        description:
          type: "string"
          description: "A description of the space"
        location:
          type: "string"
          description: "The UUID of the location of the space.  A space must be attached to a valid location."
        parent:
          type: "string"
          description: "The parent of the space.  Only contains a value if this space is a subspace, such as a corner of the kitchen or a pocket of a bag"
          